
FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["Combination.csproj", "."]
RUN dotnet restore "Combination.csproj"
COPY . .
RUN dotnet build "Combination.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Combination.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Combination.dll"]
