apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file
  template:
    metadata:
      labels:
        app: file
    spec:
      containers:
      - name: file
        image: yourdockerhubusername/file-service:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: file-service
spec:
  type: ClusterIP
  selector:
    app: file
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
